export const HOME_ROUTE = "/";
export const SIGN_IN_ROUTE = "/sign-in";
export const SIGN_UP_ROUTE = "/sign-up";
export const CHANNELS_ROUTE = "/channels";
export const USERS_ROUTE = "/users";
export const PERSONALROOM_ROUTE = "/personal-room";
export const PRICING = "/pricing";
export const RECOURCES = "/recources";
export const ENTERPRISE_ROUTE = "/enterprise ";
